version: '3.8'

services:
  timeseries:
    image: timeseries:latest
    container_name: aya_timeseries
    environment:
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=C.UTF-8
      - GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
      - PYTHON_VERSION=3.9.18
      - PYTHON_PIP_VERSION=23.0.1
      - PYTHON_SETUPTOOLS_VERSION=58.1.0
      - PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py
      - PYTHON_GET_PIP_SHA256=dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9
      - ARROW_LIBHDFS_DIR=/home/hadoop/lib/native
      - HADOOP_HOME=/home/hadoop
      - HADOOP_USER_NAME=hdfs
      - JAVA_HOME=/usr/
    volumes:
      - /home/aya/Documents/eventum/internship/ds-internship-2024:/app
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
